const SUPABASE_URL="https://aajeoloaenfewxololpj.supabase.co";const SUPABASE_KEY="sb_publishable_IwUHY90pADW53KoHEHvEtA_ik7r8Vlq";const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id);let equipment=[],events=[],locations=[],maintenance=[],scanner=null;
async function load(){const [a,b,c,d]=await Promise.all([sb.from("equipment_assets").select("*").order("equipment_item"),sb.from("events").select("*").order("start_date",{ascending:false}),sb.from("warehouse_locations").select("*").order("name"),sb.from("warehouse_maintenance").select("*").order("opened_at",{ascending:false})]);equipment=a.data||[];events=b.data||[];locations=c.data||[];maintenance=d.data||[]}
function page(p){document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===p));$("title").textContent=p==="scan"?"Scan / Check in-out":p[0].toUpperCase()+p.slice(1);render(p)}
function render(p){if(p==="dashboard")return dashboard();if(p==="equipment")return equipmentPage();if(p==="events")return tablePage("Events",events,["event_code","event_name","venue","start_date","status"]);if(p==="locations")return tablePage("Warehouse Locations",locations,["name","location_type","description"]);if(p==="maintenance")return tablePage("Maintenance",maintenance,["equipment_code","issue","priority","status","opened_at"]);if(p==="scan")return scanPage();if(p==="reports")return reports()}
function dashboard(){$("content").innerHTML='<div class="grid"><div class="stat"><label>Equipment lines</label><strong>'+equipment.length+'</strong></div><div class="stat"><label>Total units</label><strong>'+equipment.reduce((s,x)=>s+(x.total_quantity||0),0)+'</strong></div><div class="stat"><label>Available units</label><strong>'+equipment.reduce((s,x)=>s+(x.available_quantity||0),0)+'</strong></div><div class="stat"><label>Open repairs</label><strong>'+maintenance.filter(x=>x.status!=="closed").length+'</strong></div></div><div class="panel"><h3>Upcoming events</h3>'+events.slice(0,8).map(e=>'<div style="display:flex;justify-content:space-between;padding:12px 0;border-bottom:1px solid #eee"><b>'+e.event_name+'</b><span>'+ (e.start_date||"—") +' · '+(e.status||"")+'</span></div>').join("")+'</div>'}
function equipmentPage(){$("content").innerHTML='<div class="panel"><div class="toolbar"><input id="q" placeholder="Search equipment, code, category…"><button class="primary" onclick="addEquipment()">+ Add equipment</button></div><table><thead><tr><th>Code</th><th>Equipment</th><th>Category</th><th>Location</th><th>Total</th><th>Available</th><th>Condition</th></tr></thead><tbody id="rows"></tbody></table></div>';const draw=()=>{let q=($("q").value||"").toLowerCase();$("rows").innerHTML=equipment.filter(x=>(x.equipment_code+" "+x.equipment_item+" "+(x.category||"")).toLowerCase().includes(q)).map(x=>'<tr><td>'+x.equipment_code+'</td><td><b>'+x.equipment_item+'</b></td><td>'+ (x.category||"—")+'</td><td>'+ (x.location||"—")+'</td><td>'+x.total_quantity+'</td><td>'+x.available_quantity+'</td><td><span class="pill '+(x.condition==="good"?"good":"warn")+'">'+(x.condition||"unknown")+'</span></td></tr>').join("")};$("q").oninput=draw;draw()}
async function addEquipment(){let code=prompt("Equipment code");if(!code)return;let item=prompt("Equipment name");if(!item)return;let category=prompt("Category");let qty=Number(prompt("Quantity","1")||1);const r=await sb.from("equipment_assets").insert({equipment_code:code,equipment_item:item,category,total_quantity:qty,available_quantity:qty,active:true,condition:"good",maintenance_status:"ready"});if(r.error)alert(r.error.message);else{await load();equipmentPage()}}
function tablePage(title,arr,cols){$("content").innerHTML='<div class="panel"><table><thead><tr>'+cols.map(c=>'<th>'+c.replaceAll("_"," ")+'</th>').join("")+'</tr></thead><tbody>'+arr.map(x=>'<tr>'+cols.map(c=>'<td>'+(x[c]??"—")+'</td>').join("")+'</tr>').join("")+'</tbody></table></div>'}
function scanPage(){$("content").innerHTML='<div class="panel"><h3>Equipment check-in / check-out</h3><p>Enter or scan an equipment QR/code. On iPhone, the field can be filled by a Bluetooth/USB scanner or camera scanner integration.</p><div class="toolbar"><input id="scanCode" placeholder="Scan equipment code" autofocus><select id="action"><option value="checkout">Check out</option><option value="checkin">Check in</option></select><input id="scanEvent" placeholder="Event code (optional)"><input id="qty" type="number" value="1" min="1"><button class="primary" onclick="scan()">Apply</button></div><div id="scanResult"></div></div>'}
async function startScanner(){if(scanner){try{await scanner.stop()}catch{};scanner=null}$("reader").innerHTML="";scanner=new Html5Qrcode("reader");try{await scanner.start({facingMode:"environment"},{fps:10,qrbox:{width:240,height:240}},async text=>{$("scanCode").value=text;try{await scanner.stop()}catch{};scanner=null;scan()},()=>{})}catch(e){$("reader").innerHTML='<p class="danger">Camera unavailable. Check Safari camera permission and use HTTPS.</p>'}}
async function scan(){let code=$("scanCode").value.trim(),qty=Math.max(1,Number($("qty").value||1)),act=$("action").value,event=$("scanEvent").value.trim()||null;if(!code){$("scanResult").innerHTML='<p class="danger">Scan or enter an equipment code.</p>';return}$("scanResult").innerHTML="<p>Processing…</p>";const r=await sb.rpc("warehouse_scan",{p_equipment_code:code,p_action:act,p_quantity:qty,p_event_code:event,p_note:null});if(r.error){$("scanResult").innerHTML='<p class="danger">'+r.error.message+'</p>';return}await load();const d=r.data;$("scanResult").innerHTML='<p class="good">✓ '+d.equipment_item+' — available: <b>'+d.available_quantity+'</b></p>';$("scanCode").value="";$("scanCode").focus()}
function reports(){$("content").innerHTML='<div class="grid"><div class="stat"><label>Inventory lines</label><strong>'+equipment.length+'</strong></div><div class="stat"><label>Allocated/away</label><strong>'+equipment.reduce((s,x)=>s+(x.total_quantity-x.available_quantity),0)+'</strong></div><div class="stat"><label>Locations</label><strong>'+locations.length+'</strong></div><div class="stat"><label>Maintenance cases</label><strong>'+maintenance.length+'</strong></div></div><div class="panel"><h3>Inventory by category</h3>'+[...new Set(equipment.map(x=>x.category||"Uncategorised"))].map(c=>'<div style="display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #eee"><b>'+c+'</b><span>'+equipment.filter(x=>(x.category||"Uncategorised")===c).length+' lines</span></div>').join("")+'</div>'}
document.querySelectorAll(".nav").forEach(x=>x.onclick=()=>page(x.dataset.page));$("refresh").onclick=async()=>{await load();page(document.querySelector(".nav.active").dataset.page)};$("loginBtn").onclick=async()=>{let r=await sb.auth.signInWithPassword({email:$("email").value,password:$("password").value});if(r.error)$("loginMsg").textContent=r.error.message};$("logout").onclick=()=>sb.auth.signOut();
sb.auth.onAuthStateChange((event,session)=>{if(session){$("login").classList.add("hidden");$("app").classList.remove("hidden");load().then(()=>page("dashboard"))}else{$("login").classList.remove("hidden");$("app").classList.add("hidden")}});