import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const QURL='https://aajeoloaenfewxololpj.supabase.co';
const QKEY='sb_publishable_IwUHY90pADW53KoHEHvEt_A_ik7r8Vlq';
const qs=createClient(QURL,QKEY,{auth:{persistSession:true,autoRefreshToken:true}});
const qEsc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money=v=>Number(v||0).toLocaleString('en-MU',{minimumFractionDigits:2,maximumFractionDigits:2});
const qDate=v=>v?new Date(v).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}):'—';
let quotes=[],clients=[],assets=[],selected=null,items=[];
const root=()=>document.getElementById('main');
const toast=m=>{const e=document.getElementById('toast');if(e){e.textContent=m;e.classList.remove('hidden');clearTimeout(window.__qtoast);window.__qtoast=setTimeout(()=>e.classList.add('hidden'),3200);}};
function css(){if(document.getElementById('quoteCss'))return;const s=document.createElement('style');s.id='quoteCss';s.textContent=`
.quote-grid{display:grid;grid-template-columns:1.05fr .95fr;gap:14px}.quote-row{display:grid;grid-template-columns:1.2fr .7fr .45fr .6fr auto;gap:8px;align-items:center;padding:12px 0;border-top:1px solid rgba(147,177,204,.12)}.quote-row:first-child{border-top:0}.quote-input,.quote-select,.quote-area{width:100%;border:1px solid rgba(147,177,204,.18);border-radius:12px;background:#081523;color:#eef6ff;padding:11px 12px;box-sizing:border-box}.quote-area{min-height:90px;resize:vertical}.quote-summary{display:flex;justify-content:space-between;gap:12px;padding:10px 0}.quote-total{font-size:25px;font-weight:800}.quote-actions{display:flex;gap:8px;flex-wrap:wrap}.quote-list{display:grid;gap:9px}.quote-card{cursor:pointer;padding:14px;border:1px solid rgba(147,177,204,.13);border-radius:14px;background:rgba(8,21,35,.7)}.quote-card.active{border-color:rgba(71,215,255,.45)}.quote-card:hover{border-color:rgba(71,215,255,.35)}.quote-status{font-size:11px;text-transform:uppercase;letter-spacing:.08em}.quote-empty{padding:30px;text-align:center}.quote-modal{position:fixed;inset:0;background:rgba(0,0,0,.65);z-index:80;display:flex;align-items:center;justify-content:center;padding:18px}.quote-modal>div{width:min(720px,100%);max-height:90vh;overflow:auto}.quote-form{display:grid;grid-template-columns:1fr 1fr;gap:10px}.quote-form .full{grid-column:1/-1}@media(max-width:720px){.quote-grid{grid-template-columns:1fr}.quote-row{grid-template-columns:1fr 1fr}.quote-row .wide{grid-column:1/-1}.quote-form{grid-template-columns:1fr}.quote-form .full{grid-column:auto}.quote-modal{align-items:flex-start;padding:10px}.quote-total{font-size:21px}}`;
document.head.appendChild(s);}
async function session(){const r=await qs.auth.getSession();if(r.error)throw r.error;if(!r.data.session)throw new Error('Please sign in first.');return r.data.session;}
async function load(){await session();const [a,c,e]=await Promise.all([qs.from('client_quotes').select('*').order('updated_at',{ascending:false}),qs.from('client_accounts').select('profile_id,customer_code,company_name,contact_name,email,phone').eq('active',true).order('company_name'),qs.from('equipment_assets').select('equipment_code,equipment_item,category,available_quantity,active').eq('active',true).order('category').order('equipment_item')]);if(a.error)throw a.error;if(c.error)throw c.error;if(e.error)throw e.error;quotes=a.data||[];clients=c.data||[];assets=e.data||[];if(selected&&!quotes.some(q=>q.id===selected))selected=null;if(!selected)selected=quotes[0]?.id||null;await loadItems();}
async function loadItems(){items=[];if(!selected)return;const r=await qs.from('client_quote_items').select('*').eq('quote_id',selected).order('created_at');if(r.error)throw r.error;items=r.data||[];}
function quoteTotal(){return items.reduce((n,x)=>n+Number(x.total??(Number(x.quantity||0)*Number(x.unit_price||0))),0);}
function clientName(code){return clients.find(c=>c.customer_code===code)?.company_name||code||'No client';}
function render(){css();const q=quotes.find(x=>x.id===selected);root().innerHTML=`<div class="hero card"><div class="event-head"><div><div class="section-title">AV QUOTES</div><h1>Quote manager</h1><p>Create quotes with live equipment lines and push them directly into Warehouse.</p></div><button class="btn" id="newQuote">+ New quote</button></div></div><div class="quote-grid"><div><div class="card"><div class="event-head"><h2>Quotes</h2><span class="badge">${quotes.length}</span></div><div class="quote-list">${quotes.length?quotes.map(x=>`<div class="quote-card ${x.id===selected?'active':''}" data-qid="${qEsc(x.id)}"><div class="event-head"><div><strong>${qEsc(x.quote_no)}</strong><div class="tiny">${qEsc(x.event_name||'Untitled event')}</div></div><span class="quote-status badge">${qEsc(x.status||'draft')}</span></div><div class="tiny" style="margin-top:7px">${qEsc(clientName(x.customer_code))} · ${qDate(x.quote_date)}</div><strong style="display:block;margin-top:8px">MUR ${money(x.total)}</strong></div>`).join(''):'<div class="quote-empty muted">No quotes yet.</div>'}</div></div></div>${q?detail(q):'<div class="card quote-empty"><h2>Create your first quote</h2><p class="muted">Add client, event details and equipment. The equipment lines will become the warehouse pick list when you create the event.</p></div>'}</div>`;
root().querySelectorAll('[data-qid]').forEach(e=>e.onclick=async()=>{selected=e.dataset.qid;await loadItems();render();});
document.getElementById('newQuote').onclick=()=>openQuoteForm();
}
function detail(q){const total=quoteTotal();return `<div><div class="card"><div class="event-head"><div><div class="section-title">${qEsc(q.quote_no)}</div><h2>${qEsc(q.event_name||'Untitled event')}</h2><div class="tiny">${qEsc(clientName(q.customer_code))} · ${qDate(q.quote_date)}</div></div><span class="badge">${qEsc(q.status||'draft')}</span></div><div class="quote-actions" style="margin-top:12px"><button class="btn secondary" id="editQuote">Edit quote</button><button class="btn" id="createEvent">Create event + warehouse pick list</button></div></div><div class="card"><div class="event-head"><h2>Quote lines</h2><button class="btn secondary" id="addLine">+ Add line</button></div>${items.length?items.map(x=>`<div class="quote-row"><div class="wide"><strong>${qEsc(x.description)}</strong><div class="tiny">${qEsc(x.item_type)}${x.equipment_code?' · '+qEsc(x.equipment_code):''}</div></div><div>Qty <strong>${x.quantity}</strong></div><div>MUR ${money(x.unit_price)}</div><div><strong>MUR ${money(x.total)}</strong></div><button class="btn ghost" data-del="${qEsc(x.id)}">×</button></div>`).join(''):'<div class="quote-empty muted">No lines yet. Add equipment or a service.</div>'}<div class="quote-summary"><span>Total</span><span class="quote-total">MUR ${money(total)}</span></div></div><div class="card"><div class="section-title">Notes</div><p class="muted">${qEsc(q.notes||'No notes')}</p></div></div>`;}
async function openQuoteForm(){const q=quotes.find(x=>x.id===selected)||{};const modal=document.createElement('div');modal.className='quote-modal';modal.innerHTML=`<div class="card"><div class="event-head"><div><div class="section-title">QUOTE</div><h2>${q.id?'Edit quote':'New quote'}</h2></div><button class="btn ghost" id="closeQ">Close</button></div><form id="qform" class="quote-form"><div><label>Quote number</label><input class="quote-input" id="qqno" required value="${qEsc(q.quote_no||'Q-'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+String(Date.now()).slice(-4))}"></div><div><label>Status</label><select class="quote-select" id="qstatus"><option>draft</option><option>sent</option><option>accepted</option><option>declined</option><option>expired</option></select></div><div><label>Client</label><select class="quote-select" id="qclient"><option value="">Select client</option>${clients.map(c=>`<option value="${qEsc(c.customer_code||'')}" ${c.customer_code===q.customer_code?'selected':''}>${qEsc(c.company_name)}${c.customer_code?' — '+qEsc(c.customer_code):''}</option>`).join('')}</select></div><div><label>Event name</label><input class="quote-input" id="qevent" value="${qEsc(q.event_name||'')}"></div><div><label>Event code</label><input class="quote-input" id="qecode" value="${qEsc(q.event_code||'')}"></div><div><label>Quote date</label><input class="quote-input" id="qdate" type="date" value="${q.quote_date||new Date().toISOString().slice(0,10)}"></div><div><label>Valid until</label><input class="quote-input" id="qvalid" type="date" value="${q.valid_until||''}"></div><div class="full"><label>Notes</label><textarea class="quote-area" id="qnotes">${qEsc(q.notes||'')}</textarea></div><div class="actions full"><button class="btn" type="submit">Save quote</button></div></form></div>`;document.body.appendChild(modal);modal.querySelector('#qstatus').value=q.status||'draft';modal.querySelector('#closeQ').onclick=()=>modal.remove();modal.querySelector('#qform').onsubmit=async e=>{e.preventDefault();try{const s=await session();const payload={quote_no:modal.querySelector('#qqno').value.trim(),profile_id:q.profile_id||s.user.id,customer_code:modal.querySelector('#qclient').value||null,event_name:modal.querySelector('#qevent').value.trim()||null,event_code:modal.querySelector('#qecode').value.trim()||null,quote_date:modal.querySelector('#qdate').value||null,status:modal.querySelector('#qstatus').value,valid_until:modal.querySelector('#qvalid').value||null,notes:modal.querySelector('#qnotes').value.trim()||null,total:q.id?quoteTotal():0,updated_at:new Date().toISOString()};let r;if(q.id)r=await qs.from('client_quotes').update(payload).eq('id',q.id).select().single();else r=await qs.from('client_quotes').insert(payload).select().single();if(r.error)throw r.error;selected=r.data.id;modal.remove();await load();render();toast('Quote saved.');}catch(e){toast(e.message||String(e));}};}
async function addLine(){const q=quotes.find(x=>x.id===selected);if(!q)return;const modal=document.createElement('div');modal.className='quote-modal';modal.innerHTML=`<div class="card"><div class="event-head"><h2>Add quote line</h2><button class="btn ghost" id="closeL">Close</button></div><div class="field"><label>Type</label><select id="ltype" class="quote-select"><option value="equipment">Equipment</option><option value="service">Service</option></select></div><div id="equipFields"><div class="field"><label>Equipment</label><select id="lequip" class="quote-select"><option value="">Select equipment</option>${assets.map(a=>`<option value="${qEsc(a.equipment_code)}">${qEsc(a.equipment_item)} — ${qEsc(a.equipment_code)}${a.available_quantity!=null?' · avail '+a.available_quantity:''}</option>`).join('')}</select></div></div><div class="field"><label>Description</label><input id="ldesc" class="quote-input" placeholder="Equipment or service description"></div><div class="quote-form"><div><label>Quantity</label><input id="lqty" class="quote-input" type="number" min="1" value="1"></div><div><label>Unit price (MUR)</label><input id="lprice" class="quote-input" type="number" min="0" step="0.01" value="0"></div></div><div class="field"><label>Notes</label><input id="lnote" class="quote-input"></div><div class="actions"><button class="btn" id="saveLine">Add line</button></div></div>`;document.body.appendChild(modal);const type=modal.querySelector('#ltype'),ef=modal.querySelector('#equipFields'),eq=modal.querySelector('#lequip'),desc=modal.querySelector('#ldesc');type.onchange=()=>{ef.style.display=type.value==='equipment'?'block':'none';};eq.onchange=()=>{const a=assets.find(x=>x.equipment_code===eq.value);if(a)desc.value=a.equipment_item||'';};modal.querySelector('#closeL').onclick=()=>modal.remove();modal.querySelector('#saveLine').onclick=async()=>{try{const qty=Math.max(1,Number(modal.querySelector('#lqty').value||1)),price=Number(modal.querySelector('#lprice').value||0),code=type.value==='equipment'?eq.value:null;if(type.value==='equipment'&&!code)throw new Error('Select equipment.');const description=desc.value.trim();if(!description)throw new Error('Enter a description.');const a=assets.find(x=>x.equipment_code===code);const r=await qs.from('client_quote_items').insert({quote_id:q.id,item_type:type.value,equipment_code:code,description,category:a?.category||null,quantity:qty,unit_price:price,total:qty*price,notes:modal.querySelector('#lnote').value.trim()||null}).select().single();if(r.error)throw r.error;const nr=await qs.from('client_quotes').update({total:quoteTotal()+qty*price,updated_at:new Date().toISOString()}).eq('id',q.id);if(nr.error)throw nr.error;modal.remove();await load();render();toast('Line added.');}catch(e){toast(e.message||String(e));}};}
async function createEvent(){const q=quotes.find(x=>x.id===selected);if(!q) return;try{const s=await session();const code=q.event_code||('EV-'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+Math.random().toString(36).slice(2,6).toUpperCase());const eventName=q.event_name||'Event from '+q.quote_no;const r=await qs.from('events').insert({event_code:code,event_name:eventName,client_name:clientName(q.customer_code),status:'draft',source_quote_id:q.id,source_quote_no:q.quote_no}).select().single();if(r.error)throw r.error;const sync=await qs.rpc('sync_quote_to_event',{p_quote_id:q.id,p_event_code:code});if(sync.error)throw sync.error;const up=await qs.from('client_quotes').update({event_code:code,status:q.status==='accepted'?'accepted':q.status,updated_at:new Date().toISOString()}).eq('id',q.id);if(up.error)throw up.error;await load();render();toast('Event '+code+' created and '+Number(sync.data||0)+' equipment lines synced to Warehouse.');}catch(e){toast(e.message||String(e));}}
root().addEventListener('click',async e=>{const del=e.target.closest('[data-del]');if(del){if(!confirm('Delete this quote line?'))return;const r=await qs.from('client_quote_items').delete().eq('id',del.dataset.del);if(r.error){toast(r.error.message);return;}await loadItems();const t=quoteTotal();await qs.from('client_quotes').update({total:t,updated_at:new Date().toISOString()}).eq('id',selected);await load();render();return;}if(e.target.id==='editQuote')openQuoteForm();if(e.target.id==='addLine')addLine();if(e.target.id==='createEvent')createEvent();});
async function showQuotes(){document.getElementById('tabEvents')?.classList.remove('active');document.getElementById('tabGear')?.classList.remove('active');document.getElementById('tabAlerts')?.classList.remove('active');document.getElementById('tabQuotes')?.classList.add('active');try{await load();render();}catch(e){toast(e.message||String(e));}}
document.addEventListener('DOMContentLoaded',()=>document.getElementById('tabQuotes')?.addEventListener('click',showQuotes));
