import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const U='https://aajeoloaenfewxololpj.supabase.co',K='sb_publishable_IwUHY90pADW53KoHEHvEt_A_ik7r8Vlq',s=createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true}});
let rows=[];
const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const toast=m=>{const t=document.getElementById('toast');if(t){t.textContent=m;t.classList.remove('hidden');clearTimeout(window.__rs);window.__rs=setTimeout(()=>t.classList.add('hidden'),2800)}};
function css(){if(document.getElementById('responseCss'))return;const x=document.createElement('style');x.id='responseCss';x.textContent='.crew-response{margin-top:12px;padding-top:12px;border-top:1px solid rgba(147,177,204,.12)}.crew-response .status-line{display:flex;justify-content:space-between;gap:10px;align-items:center}.crew-response .rs-actions{display:flex;gap:8px;margin-top:8px}.crew-response .accept{background:#47d7ff;color:#07111f}.crew-response .decline{background:#381b24;color:#ffc0c7;border:1px solid rgba(255,192,199,.15)}';document.head.appendChild(x)}
async function refreshRows(){const g=await s.auth.getSession();if(!g.data.session){rows=[];return}const r=await s.from('crew_event_assignments').select('id,event_code,response_status,events!crew_event_assignments_event_id_fkey(event_code,event_name)').order('call_time',{ascending:true});if(r.error){console.warn(r.error);return}rows=r.data||[]}
function codeOf(card){return card.querySelector('.tiny')?.textContent?.trim()?.split(/\s+/)[0]||''}
function decorate(){css();document.querySelectorAll('#main .event').forEach(card=>{const code=codeOf(card),row=rows.find(x=>String(x.event_code||x.events?.event_code||'')===code);if(!row)return;const st=row.response_status||'Pending';let box=card.querySelector('.crew-response');if(!box){box=document.createElement('div');box.className='crew-response';card.appendChild(box)}box.innerHTML='<div class="status-line"><span class="tiny">Crew response</span><span class="badge">'+esc(st)+'</span></div><div class="rs-actions"><button class="btn accept" '+(st==='Accepted'?'disabled':'')+'>Accept</button><button class="btn decline" '+(st==='Declined'?'disabled':'')+'>Decline</button></div>';box.querySelector('.accept').onclick=()=>setResponse(row.id,'Accepted');box.querySelector('.decline').onclick=()=>setResponse(row.id,'Declined')})}
async function setResponse(id,value){const g=await s.auth.getSession();if(!g.data.session){toast('Please sign in first.');return}const r=await s.from('crew_event_assignments').update({response_status:value,response_at:new Date().toISOString()}).eq('id',id).eq('crew_user_id',g.data.session.user.id);if(r.error){toast(r.error.message);return}const row=rows.find(x=>x.id===id);if(row)row.response_status=value;toast(value==='Accepted'?'Crew call accepted.':'Crew call declined.');decorate()}
async function boot(){await refreshRows();decorate();const main=document.getElementById('main');if(main)new MutationObserver(()=>decorate()).observe(main,{childList:true,subtree:true});setInterval(async()=>{await refreshRows();decorate()},30000)}
boot().catch(e=>console.warn('Crew response module failed',e));