import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const RS_URL='https://aajeoloaenfewxololpj.supabase.co';
const RS_KEY='sb_publishable_IwUHY90pADW53KoHEHvEt_A_ik7r8Vlq';
const rs=createClient(RS_URL,RS_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
let responseRows=[];

const rsToast=m=>{const t=document.getElementById('toast');if(t){t.textContent=m;t.classList.remove('hidden');clearTimeout(window.__rs);window.__rs=setTimeout(()=>t.classList.add('hidden'),2800)}};
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const css=()=>{if(document.getElementById('responseCss'))return;const s=document.createElement('style');s.id='responseCss';s.textContent='.crew-response{margin-top:12px;padding-top:12px;border-top:1px solid rgba(147,177,204,.12)}.crew-response .status-line{display:flex;justify-content:space-between;gap:10px;align-items:center}.crew-response .rs-actions{display:flex;gap:8px;margin-top:8px}.crew-response .accept{background:#47d7ff;color:#07111f}.crew-response .decline{background:#381b24;color:#ffc0c7;border:1px solid rgba(255,192,199,.15)}';document.head.appendChild(s)};
async function loadResponses(){const r=await rs.auth.getSession();if(!r.data.session){responseRows=[];return}const q=await rs.from('crew_event_assignments').select('id,event_code,event_id,response_status,response_at,status,events!crew_event_assignments_event_id_fkey(event_code,event_name)').order('call_time',{ascending:true});if(q.error){console.warn(q.error);return}responseRows=q.data||[];}
async function setResponse(id,value){const r=await rs.auth.getSession();if(!r.data.session){rsToast('Please sign in first.');return}const u=await rs.from('crew_event_assignments').update({response_status:value,response_at:new Date().toISOString()}).eq('id',id).eq('crew_user_id',r.data.session.user.id);if(u.error){rsToast(u.error.message);return}const row=responseRows.find(x=>x.id===id);if(row)row.response_status=value;rsToast(value==='Accepted'?'Crew call accepted.':'Crew call declined.');decorate();}
function eventCodeFromCard(card){const tiny=card.querySelector('.tiny');return tiny?.textContent?.trim()?.split(/\s+/)[0]||'';}
function decorate(){css();document.querySelectorAll('#main .event').forEach(card=>{if(card.querySelector('.crew-response'))return;const code=eventCodeFromCard(card);const row=responseRows.find(x=>String(x.event_code||x.events?.event_code||'')===code);if(!row)return;const status=row.response_status||'Pending';const box=document.createElement('div');box.className='crew-response';box.innerHTML='<div class="status-line"><span class="tiny">Crew response</span><span class="badge">'+esc(status)+'</span></div><div class="rs-actions"><button class="btn accept" '+(status==='Accepted'?'disabled':'')+'>Accept</button><button class="btn decline" '+(status==='Declined'?'disabled':'')+'>Decline</button></div>';box.querySelector('.accept').onclick=()=>setResponse(row.id,'Accepted');box.querySelector('.decline').onclick=()=>setResponse(row.id,'Declined');card.appendChild(box);});}
async function bootResponses(){await loadResponses();decorate();const main=document.getElementById('main');if(main){new MutationObserver(()=>decorate()).observe(main,{childList:true,subtree:true});setInterval(loadResponses,30000);}}
bootResponses().catch(e=>console.warn('Crew response module failed',e));